config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  get 'about', to: 'homes#about', as: :about
  resources :posts
  resources :comments
  resources :categories
  devise_for :users,:controllers => { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  get 'users/profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts, dependent: :destroy
	belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :description, presence: true



	has_one_attached :image
	has_many :comments, dependent: :delete_all
	belongs_to :category
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :posts, dependent: :delete_all
  has_many :categories, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  def index
  	@category = Category.all
  end

  def show
  end

  def edit
  end

  def new
    @user = current_user
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	@category.save
  	redirect_to new_post_path
  end

  private
  	def category_params
  		params.require(:category).permit(:name, :user_id);
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  	@comment = Comment.all
  end

  def new
  	@comment = Comment.new
  end


  def create
  	@comment = Comment.new(comment_params)
  	@comment.save
    @post = @comment.post
  	redirect_to @post
  end

  private	
	def comment_params
		params.require(:comment).permit(:name, :body, :post_id)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  	@post = Post.all.limit(6)
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def index
  	@post = Post.all
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def edit
    @user = current_user
  	@post = Post.find(params[:id])
  end

  def show
    @comment = Comment.new
  	@post = Post.find(params[:id])
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  	 redirect_to @post, notice: 'successfully created post.'
    else
      redirect_to new_post_path, notice: 'try again'
    end
  end

  def update
    @post =  Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to posts_path
  end

  private
   def post_params
   	params.require(:post).permit(:title, :description, :category_id, :image, :user_id)	
   end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

   protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :phone, :name])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:image, :phone, :name])
   end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
    # super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

   protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
  	@user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |form|%>
<%= form.hidden_field :user_id, value: @user.id%>
<%=form.label :name %>
<%=form.text_field :name %>
<%= form.submit%>
<%end%>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<%= link_to 'new category', new_category_path %>
<br>
<br>

	<table border="1px">
		<tr>
			<th>category name</th>
			
		</tr>
		<% @category.each do |category|%>
		
			<tr>
				<td><%= category.name %></td>
				
			</tr>
			
		<%end%>
	</table>

app/views/categories/new.html.erb
<%=render 'form'%>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/comments/_form.html.erb
<%= form_with model: @comment, :remote => true do |form| %>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<%= form.label :Description %>
	<%= form.text_field :body %>
	<%= form.hidden_field :post_id, value:@post.id %>
	<%= form.submit 'new comment'%>
<%end%>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
	<%= f.hidden_field :user_id, value: @user.id %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :Description %>
	<%= f.text_field :description %>
	<%= f.label :image %>
	<%= f.file_field :image %>
	
	<%= f.collection_select :category_id, Category.all, :id, :name, :prompt => 'Select' %>
	<%=f.submit%>
<%end%>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to 'new post', new_post_path %>

<br>
<br>

	<table border="1px">
		<tr>
			<th>Title</th>
			<th>description</th>
			<% if user_signed_in?%>
			<th>edit</th>
			<th>delete</th>
			<%end%>
			<th>show</th>
			
		</tr>
		<% @post.each do |post|%>
			<tr>
				<td><%= post.title %></td>
				<td><%= post.description%></td>
				
				<% if current_user == post.user %>
				<td><%= link_to 'Edit', edit_post_path(post) %></td>
				<td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
				<td><%= link_to 'Show', post_path(post) %></td>
			</tr>
		<%end%>
	</table>
	

app/views/posts/new.html.erb
<%= render 'form'%>

app/views/posts/show.html.erb
<strong>Title</strong><br>
<%= @post.title %><br>
<strong>Description</strong><br>
<%= @post.description %><br>
<strong>category</strong><br>
<%= @post.category.name%><br>
<%= image_tag (@post.image) if @post.image.attached?%><br>
<%= link_to 'edit', edit_post_path %><br>
<hr>
<% @post.comments.each do |comment|%>
	<strong>Name</strong><br>
	<%= comment.name %><br>
	<strong>comment description</strong><br>
	<%= comment.body %><br><br>
<%end%>
<%= render 'comments/form' %>

app/views/users/profile.html.erb
<%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-primary mt-3' %>
<%= @user.email%>
<%= @user.phone%>
<%= @user.name%>
<%= image_tag (@user.image) if @user.image.attached?%>
<br>
<% current_user.posts.each do |post|%>
<strong>post name</strong>
<%=post.title%>
<%end%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>