config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  get 'about', to: 'homes#about', as: :about
  resources :posts
  resources :comments
  resources :categories
  devise_for :users,:controllers => { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  get 'users/profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts, dependent: :destroy
	belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :description, presence: true



	has_one_attached :image
	has_many :comments, dependent: :delete_all
	belongs_to :category
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :posts, dependent: :delete_all
  has_many :categories, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  def index
  	@category = Category.all
  end

  def show
  end

  def edit
  end

  def new
    @user = current_user
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	@category.save
  	redirect_to new_post_path
  end

  private
  	def category_params
  		params.require(:category).permit(:name, :user_id);
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  	@comment = Comment.all
  end

  def new
  	@comment = Comment.new
  end


  def create
  	@comment = Comment.new(comment_params)
  	@comment.save
    @post = @comment.post
  	redirect_to @post
  end

  private	
	def comment_params
		params.require(:comment).permit(:name, :body, :post_id)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  	@post = Post.all.limit(6)
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def index
  	@post = Post.all
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def edit
    @user = current_user
  	@post = Post.find(params[:id])
  end

  def show
    @comment = Comment.new
  	@post = Post.find(params[:id])
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  	 redirect_to @post, notice: 'successfully created post.'
    else
      redirect_to new_post_path, notice: 'try again'
    end
  end

  def update
    @post =  Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to posts_path
  end

  private
   def post_params
   	params.require(:post).permit(:title, :description, :category_id, :image, :user_id)	
   end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

   protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

   protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
  	@user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= about_path %>">About</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>">Posts</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="<%= categories_path %>">categories</a>
        </li>
        <% if user_signed_in? %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= current_user.name%>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= users_profile_path %>">
              My Profile
            </a>
             <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete">
              Logout
            </a>
            
          </div>
        </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_session_path %>">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up">Sign up</a>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <% if notice %>
   <p class="alert alert-success"><%= notice %></p> 
<% end %>
<% if alert %>
 <p class="alert alert-danger"><%= alert %></p> 
<% end %>

    <%= yield %>
   
  </body>

</html>